# Soraya charkas 99101387

# Q1

A Hebbian neuron is a type of artificial neuron inspired by the Hebbian theory of learning, which states that when two neurons are activated simultaneously, the strength of the connection between them is strengthened. In other words, "neurons that fire together, wire together."
In the context of artificial neural networks, a Hebbian neuron is a neuron that modifies the strength of its connections to other neurons based on the activation patterns of those neurons. Specifically, when the output of a Hebbian neuron is high, it increases the strength of its connections to the neurons that contributed to that output, and when the output is low, it decreases the strength of those connections.
Hebbian neurons can be used in multi-layer neural networks, but they are typically used only in the input layer, where they modify the weights of the connections between the input neurons and the neurons in the next layer. In deeper layers of the network, other types of neurons, such as sigmoid or rectified linear units (ReLU), are more commonly used. This is because Hebbian learning can lead to instability and overfitting in deeper layers due to the "exploding gradient" problem, where the weights become so large that the network becomes unstable and cannot learn effectively.
Therefore, while Hebbian neurons can be used in multi-layer models, they are typically used only in the input layer and other types of neurons are used in the deeper layers.

# Q2

When the patterns in Hebbian learning are orthogonal, we expect the learning to be more efficient and the resulting representations to be more distinct and separable.
In Hebbian learning, the strength of the connection between two neurons is modified based on the co-activation of those neurons. If the patterns are orthogonal, meaning that they are mutually exclusive and have no overlap, the neurons will be activated independently and thus their connections will be modified independently. This means that the connections between neurons that correspond to different patterns will be strengthened, while connections between neurons that correspond to similar patterns will be weakened or unchanged. orthogonal patterns can also reduce the problem of interference in the learning process. Interference occurs when learning one pattern disrupts the learned representation of another pattern. Since orthogonal patterns are mutually exclusive, learning one pattern does not interfere with the learned representation of another pattern, making the learning process more efficient.

In [ ]:
#necessary packages
import numpy as np

# Q3

first, we define the "Hebbian_learning" function and the "output" function

In [162]:
#necesary functions
def Hebbian_learning(weights, word, target):
    target_vec = np.zeros(7)
    target_vec[target] = 1
    weights[0:7, 0:35] += np.outer(target_vec, word)
    weights[7, 0] += 1
    return weights
## -------------------------------
def Train(weights, word):
    weights_no_bias = weights[:, :35]
    activations = np.matmul(weights_no_bias, word.T)
    result = (activations >= weights[7, 0]).astype(float)
    return result.T
## -------------------------------
def Train2(weights , word): 
    result = np.zeros((1,7) , dtype = float)
    for i in range (7):
        act = np.matmul(weights [i , 0:35] , word)
        if act >= weights [7][0] :
            result [0][i] = 1
        else :
            result [0][i] = -1
    return result
## -------------------------------
def Binary_Polar(char):
    for i in range (7):
        for j in range (3):
            for k in range (35):
                if (char[i][j][k] == 0):
                    char[i][j][k] = -1
    return char
## -------------------------------
def Hebbian_learning_2(weights, word, target):
    for i in range(7):
        if i == target:
            weights[i, 0:35] += word
            weights[7][0] += 1
        else:
            weights[i, 0:35] -= word
            weights[7][0] -= 1
    return weights


here,we define our patterns and tests for letters A,X,O,E,Z,T,L

In [152]:
pattern = np.zeros((7,3,35),dtype=float )
# Define the patterns for character A
pattern[0,0,:]= [0,0,1,0,0,0,1,0,1,0,1,1,1,1,1,1,0,0,0,1,1,0,0,0,1,1,0,0,0,1,1,0,0,0,1]

pattern[0,1,:]= [0,0,1,0,0,0,1,0,1,0,1,1,1,1,1,1,0,0,0,1,1,0,0,0,1,1,0,0,0,1,0,0,0,0,0]

pattern[0,2,:]= [0,1,1,1,0,1,0,0,0,1,1,0,0,0,0,1,1,1,1,0,1,0,0,0,1,1,0,0,0,1,0,0,0,0,0]

# Define the patterns for character X
pattern[1,0,:]= [1,0,0,0,1,0,1,0,1,0,0,0,1,0,0,0,1,0,1,0,1,0,0,0,1,0,1,0,1,0,0,0,1,0,0]

pattern[1,1,:]= [1,0,0,0,1,0,1,0,1,0,0,0,1,0,0,0,1,0,1,0,1,0,0,0,1,1,1,1,1,1,0,0,0,0,0]

pattern[1,2,:]= [1,0,0,0,1,0,1,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,1,0,1,0,0,0,1,1,1,1,1,1]
# Define the patterns for character O
pattern[3,0,:]= [0,1,1,1,0,1,0,0,0,1,1,0,0,0,1,1,0,0,0,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0]

pattern[3,1,:]= [0,0,1,0,0,0,1,0,1,0,1,0,0,0,1,1,0,0,0,1,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0]

pattern[3,2,:]= [0,0,1,1,0,0,1,0,0,1,1,0,0,0,1,1,0,0,0,1,0,1,0,0,1,0,0,1,1,0,0,0,0,0,0]
# Define the patterns for character L
pattern[4,0,:]= [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,1,1,1,1]

pattern[4,1,:]= [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,1,0,1,1]

pattern[4,2,:]= [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,1,1,1,0]

# Define the patterns for character T
pattern[5,0,:]= [1,1,1,1,1,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0]

pattern[5,1,:]= [1,1,1,1,1,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0]

pattern[5,2,:]= [1,1,1,1,1,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0]

# Define the patterns for character Z
pattern[6,0,:]= [1,1,1,1,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,1,1,1,1]

pattern[6,1,:]= [1,1,1,1,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,1,1,1,0]

pattern[6,2,:]= [1,1,1,1,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0]

# Define the patterns for character E

pattern[2,0,:]= [1,1,1,1,1,1,0,0,0,0,1,0,0,0,0,1,1,1,1,1,1,0,0,0,0,1,0,0,0,0,1,1,1,1,1]

pattern[2,1,:]= [1,1,1,1,1,1,0,0,0,0,1,0,0,0,0,1,1,1,1,1,1,0,0,0,0,1,1,1,1,1,0,0,0,0,0]

pattern[2,2,:]=[1,1,1,1,1,1,0,0,0,0,1,0,0,0,0,1,1,1,1,1,1,0,0,0,0,1,0,0,0,0,1,1,1,1,0]



patternTest = np.zeros((7,3,35),dtype=float )
# Define the testing patterns for character A
patternTest[0,1,:] = [0,0,1,0,0,0,1,0,1,0,1,1,0,1,1,1,0,0,0,1,1,0,0,0,1,1,0,0,0,1,1,0,0,0,0]

patternTest[0,0,:] = [0,0,1,0,0,0,1,0,1,0,1,0,1,1,1,1,0,0,0,1,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0]

# Define the testing patterns for character X
patternTest[1,0,:] = [1,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,1,0,1,0,1,0,0,0,0,0,0]

patternTest[1,1,:] = [1,0,0,0,1,0,1,0,1,0,0,0,1,0,0,0,1,0,1,0,1,0,0,0,1,1,1,0,0,1,0,0,0,0,0]


# Define the patterns for character O
patternTest[2,0,:] = [0,1,1,1,0,1,0,0,0,1,1,0,0,0,1,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0]

patternTest[2,1,:] = [0,0,0,0,0,0,1,0,1,0,1,0,0,0,1,1,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0]

# Define the testing patterns for character L
patternTest[3,0,:] =[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,1,1,0,1]

patternTest[3,1,:] = [1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,1,0,0,1]
    
# Define the patterns for character T
patternTest[4,0,:] = [1,1,1,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0]

patternTest[4,1,:] = [1,1,1,1,1,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]

# Define the testing patterns for character Z
patternTest[5,0,:] = [1,1,1,1,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1]

patternTest[5,1,:] = [1,0,0,1,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,1,1,1,1,0]

# Define the patterns for character E

patternTest[6,0,:] = [1,1,1,1,1,1,0,0,0,0,1,0,0,0,0,1,1,1,0,0,1,0,0,0,0,1,0,0,0,0,1,1,1,1,1]

patternTest[6,1,:] = [1,1,1,1,1,1,0,0,0,0,1,0,0,0,0,1,1,1,1,1,1,0,0,0,0,1,0,1,1,0,0,0,0,0,0]



using the written function, we now train our neurons:

In [153]:
weights = np.zeros((8 , 35) , dtype = float) 
for i, j in np.ndindex((7, 3)):
    Hebbian_learning(weights, pattern[i, j, :], i)

In [154]:
for i in range(7):
    print("pattern " + str(i))
    print("_____________________________")
    for j in range(3):
        print(" ",Train(weights , pattern[i,j,:]))
        

pattern 0
_____________________________
  [1. 0. 1. 0. 0. 0. 0. 0.]
  [1. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 0. 0. 0. 0.]
pattern 1
_____________________________
  [0. 1. 0. 0. 0. 0. 0. 1.]
  [0. 1. 1. 0. 0. 0. 0. 1.]
  [0. 1. 1. 0. 0. 0. 1. 1.]
pattern 2
_____________________________
  [1. 1. 1. 0. 1. 0. 1. 1.]
  [1. 1. 1. 0. 0. 0. 1. 1.]
  [1. 0. 1. 0. 1. 0. 1. 1.]
pattern 3
_____________________________
  [0. 0. 1. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0.]
pattern 4
_____________________________
  [0. 0. 1. 0. 1. 0. 0. 1.]
  [0. 0. 1. 0. 1. 0. 0. 1.]
  [0. 0. 1. 0. 1. 0. 0. 1.]
pattern 5
_____________________________
  [0. 0. 1. 0. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0. 1. 0. 1.]
  [0. 0. 1. 0. 0. 1. 0. 1.]
pattern 6
_____________________________
  [0. 0. 1. 0. 0. 0. 1. 1.]
  [0. 0. 1. 0. 0. 0. 1. 1.]
  [0. 0. 1. 0. 0. 0. 1. 1.]


It is evident that the correct answer was obtained at A2-L1-L2. Prior to examination, it was observed that 'L' would be a suitable selection due to its orthogonality with a majority of the characters.The error rate is found to be considerably high, with an accuracy of only 14.28%, indicating poor performance of the algorithm. Random selection of words would result in an accuracy of approximately 13.5%, revealing the inadequacy of the algorithm.in this case, we examined our algorithm using the patterns we train it,lets see what happens if we use different patterns:

In [155]:
for i in range(7):
    print("pattern " + str(i))
    print("_____________________________")
    for j in range(2):
        print(" ",Train(weights , patternTest[i,j,:]))

pattern 0
_____________________________
  [1. 0. 0. 0. 0. 0. 0. 0.]
  [1. 0. 1. 0. 0. 0. 0. 0.]
pattern 1
_____________________________
  [0. 1. 0. 0. 0. 0. 0. 1.]
  [0. 1. 0. 0. 0. 0. 0. 1.]
pattern 2
_____________________________
  [0. 0. 1. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
pattern 3
_____________________________
  [0. 0. 1. 0. 1. 0. 0. 1.]
  [0. 0. 1. 0. 1. 0. 0. 1.]
pattern 4
_____________________________
  [0. 0. 0. 0. 0. 1. 0. 1.]
  [0. 0. 0. 0. 0. 1. 0. 1.]
pattern 5
_____________________________
  [0. 0. 1. 0. 0. 0. 1. 1.]
  [0. 0. 1. 0. 0. 0. 1. 1.]
pattern 6
_____________________________
  [1. 0. 1. 0. 1. 0. 1. 1.]
  [1. 0. 1. 0. 0. 0. 1. 1.]


Upon utilizing various patterns, the accuracy of the classification dropped to a third of the original value, declining from 14.28% to 4.7%. This indicates that the use of the Hebbian algorithm for learning is not effective, and that successful classification is not achieved. While the algorithm is able to correctly identify the target word in some cases, it indiscriminately groups together other words in the classification process.

# Q4

we have to define a new training function.it is visible to you in the first cell named "Train2"

In [156]:
weights = np.zeros((8 , 35) , dtype = float) 
for i, j in np.ndindex((7, 3)):
    Hebbian_learning(weights, pattern[i, j, :], i)
    

In [157]:
for i in range(7):
    print("pattern " + str(i))
    print("_____________________________")
    for j in range(3):
        print(" ",Train2(weights , pattern[i,j,:]))

pattern 0
_____________________________
  [[ 1. -1.  1. -1. -1. -1. -1.]]
  [[ 1. -1. -1. -1. -1. -1. -1.]]
  [[ 1. -1.  1. -1. -1. -1. -1.]]
pattern 1
_____________________________
  [[-1.  1. -1. -1. -1. -1. -1.]]
  [[-1.  1.  1. -1. -1. -1. -1.]]
  [[-1.  1.  1. -1. -1. -1.  1.]]
pattern 2
_____________________________
  [[ 1.  1.  1. -1.  1. -1.  1.]]
  [[ 1.  1.  1. -1. -1. -1.  1.]]
  [[ 1. -1.  1. -1.  1. -1.  1.]]
pattern 3
_____________________________
  [[-1. -1.  1.  1. -1. -1. -1.]]
  [[-1. -1. -1.  1. -1. -1. -1.]]
  [[-1. -1. -1.  1. -1. -1. -1.]]
pattern 4
_____________________________
  [[-1. -1.  1. -1.  1. -1. -1.]]
  [[-1. -1.  1. -1.  1. -1. -1.]]
  [[-1. -1.  1. -1.  1. -1. -1.]]
pattern 5
_____________________________
  [[-1. -1.  1. -1. -1.  1. -1.]]
  [[-1. -1. -1. -1. -1.  1. -1.]]
  [[-1. -1.  1. -1. -1.  1. -1.]]
pattern 6
_____________________________
  [[-1. -1.  1. -1. -1. -1.  1.]]
  [[-1. -1.  1. -1. -1. -1.  1.]]
  [[-1. -1.  1. -1. -1. -1.  1.]]


as we expected,the results are the same as our first examination.lets try it out with new patters:

In [158]:
for i in range(7):
    print("pattern " + str(i))
    print("_____________________________")
    for j in range(2):
        print(" ",Train2(weights , patternTest[i,j,:]))

pattern 0
_____________________________
  [[ 1. -1. -1. -1. -1. -1. -1.]]
  [[ 1. -1.  1. -1. -1. -1. -1.]]
pattern 1
_____________________________
  [[-1.  1. -1. -1. -1. -1. -1.]]
  [[-1.  1. -1. -1. -1. -1. -1.]]
pattern 2
_____________________________
  [[-1. -1.  1.  1. -1. -1. -1.]]
  [[-1. -1. -1. -1. -1. -1. -1.]]
pattern 3
_____________________________
  [[-1. -1.  1. -1.  1. -1. -1.]]
  [[-1. -1.  1. -1.  1. -1. -1.]]
pattern 4
_____________________________
  [[-1. -1. -1. -1. -1.  1. -1.]]
  [[-1. -1. -1. -1. -1.  1. -1.]]
pattern 5
_____________________________
  [[-1. -1.  1. -1. -1. -1.  1.]]
  [[-1. -1.  1. -1. -1. -1.  1.]]
pattern 6
_____________________________
  [[ 1. -1.  1. -1.  1. -1.  1.]]
  [[ 1. -1.  1. -1. -1. -1.  1.]]


The application of the bipolar algorithm yielded a superior outcome, with 5 out of 14 characters being accurately detected, resulting in an accuracy of 35.7%, a significant improvement from the previous results. The character 'T' exhibited the optimal response, attributed to its orthogonality with the remaining characters.

now,we convert our patterns to bipolar form:

In [166]:
pattern=Binary_Polar(pattern)
weights = np.zeros((8 , 35) , dtype = float) 
for i, j in np.ndindex((7, 3)):
    Hebbian_learning(weights, pattern[i, j, :], i)
    
for i in range(7):
    print("pattern " + str(i))
    print("_____________________________")
    for j in range(3):
        print(" ",Train2(weights , pattern[i,j,:]))    

pattern 0
_____________________________
  [[ 1. -1. -1. -1. -1. -1. -1.]]
  [[ 1. -1. -1.  1. -1. -1. -1.]]
  [[ 1. -1.  1. -1. -1. -1. -1.]]
pattern 1
_____________________________
  [[-1.  1. -1. -1. -1. -1. -1.]]
  [[-1.  1. -1. -1. -1. -1. -1.]]
  [[-1.  1. -1. -1.  1. -1.  1.]]
pattern 2
_____________________________
  [[-1. -1.  1. -1.  1. -1.  1.]]
  [[-1. -1.  1. -1. -1. -1. -1.]]
  [[-1. -1.  1. -1.  1. -1.  1.]]
pattern 3
_____________________________
  [[-1. -1. -1.  1. -1. -1. -1.]]
  [[ 1. -1. -1.  1. -1. -1. -1.]]
  [[ 1. -1. -1.  1. -1. -1. -1.]]
pattern 4
_____________________________
  [[-1. -1.  1. -1.  1. -1.  1.]]
  [[-1. -1.  1. -1.  1. -1.  1.]]
  [[-1. -1.  1. -1.  1. -1.  1.]]
pattern 5
_____________________________
  [[-1. -1. -1. -1. -1.  1.  1.]]
  [[-1. -1. -1. -1. -1.  1.  1.]]
  [[-1. -1. -1. -1. -1.  1.  1.]]
pattern 6
_____________________________
  [[-1. -1.  1. -1.  1.  1.  1.]]
  [[-1. -1.  1. -1.  1.  1.  1.]]
  [[-1. -1. -1.  1. -1.  1.  1.]]


Upon examination, the algorithm was found to detect 6 out of 21 characters, indicating an accuracy rate of 42.8%. Implementing the bipolar form resulted in an improved outcome, aligning with our expectations.

and for noisy pattern we have :

In [167]:
for i in range(7):
    print("pattern " + str(i))
    print("_____________________________")
    for j in range(2):
        print(" ",Train2(weights , patternTest[i,j,:]))  

pattern 0
_____________________________
  [[ 1. -1. -1. -1. -1. -1. -1.]]
  [[ 1. -1. -1. -1. -1. -1. -1.]]
pattern 1
_____________________________
  [[-1. -1. -1. -1. -1. -1. -1.]]
  [[-1.  1. -1. -1. -1. -1. -1.]]
pattern 2
_____________________________
  [[-1. -1. -1. -1. -1. -1. -1.]]
  [[-1. -1. -1. -1. -1. -1. -1.]]
pattern 3
_____________________________
  [[-1. -1. -1. -1.  1. -1. -1.]]
  [[-1. -1. -1. -1.  1. -1. -1.]]
pattern 4
_____________________________
  [[-1. -1. -1. -1. -1.  1. -1.]]
  [[-1. -1. -1. -1. -1.  1. -1.]]
pattern 5
_____________________________
  [[-1. -1. -1. -1. -1. -1.  1.]]
  [[-1. -1. -1. -1. -1. -1.  1.]]
pattern 6
_____________________________
  [[-1. -1.  1. -1. -1. -1. -1.]]
  [[-1. -1.  1. -1. -1. -1. -1.]]


the result is shocking!we got 9 out of 14 algorithms correct which is nearly 65% accuracy

# Q5

The results were derived from the preceding sections, indicating an accuracy of 4.7% for binary input, 35% for binary input in the bipolar model, and 65% for bipolar input and output. As anticipated, the bipolar form demonstrated superior performance, exhibiting resilience in the presence of noisy input, surpassing the performance of other algorithms.Overall, the Hebbian algorithms exhibit little variation in performance between noisy and non-noisy input, with outputs showing minimal deviation. This resilience to noise highlights the algorithm's robustness against interference.

# Q6

In [165]:
weights = np.zeros((8 , 35) , dtype = float) 
for i, j in np.ndindex((7, 3)):
    Hebbian_learning_2(weights, pattern[i, j, :], i)
    
for i in range(7):
    print("pattern " + str(i))
    print("_____________________________")
    for j in range(3):
        print(" ",Train2(weights , pattern[i,j,:]))  

pattern 0
_____________________________
  [[1. 1. 1. 1. 1. 1. 1.]]
  [[1. 1. 1. 1. 1. 1. 1.]]
  [[ 1. -1.  1.  1.  1. -1. -1.]]
pattern 1
_____________________________
  [[1. 1. 1. 1. 1. 1. 1.]]
  [[1. 1. 1. 1. 1. 1. 1.]]
  [[ 1.  1.  1. -1.  1.  1.  1.]]
pattern 2
_____________________________
  [[-1. -1.  1. -1.  1. -1.  1.]]
  [[ 1. -1.  1. -1.  1.  1. -1.]]
  [[-1. -1.  1. -1.  1. -1. -1.]]
pattern 3
_____________________________
  [[ 1. -1.  1.  1.  1.  1.  1.]]
  [[ 1.  1. -1.  1.  1.  1.  1.]]
  [[1. 1. 1. 1. 1. 1. 1.]]
pattern 4
_____________________________
  [[-1. -1.  1. -1.  1. -1. -1.]]
  [[-1. -1. -1. -1.  1. -1. -1.]]
  [[-1. -1. -1. -1.  1. -1. -1.]]
pattern 5
_____________________________
  [[-1. -1. -1. -1. -1.  1.  1.]]
  [[-1. -1. -1. -1. -1.  1.  1.]]
  [[-1. -1. -1. -1. -1.  1.  1.]]
pattern 6
_____________________________
  [[-1. -1. -1. -1.  1.  1.  1.]]
  [[-1. -1. -1. -1. -1.  1.  1.]]
  [[-1. -1. -1. -1. -1.  1.  1.]]


and for the noisy input we have :

In [168]:
for i in range(7):
    print("pattern " + str(i))
    print("_____________________________")
    for j in range(2):
        print(" ",Train2(weights , patternTest[i,j,:]))  

pattern 0
_____________________________
  [[ 1. -1. -1. -1. -1. -1. -1.]]
  [[ 1. -1. -1. -1. -1. -1. -1.]]
pattern 1
_____________________________
  [[-1. -1. -1. -1. -1. -1. -1.]]
  [[-1.  1. -1. -1. -1. -1. -1.]]
pattern 2
_____________________________
  [[-1. -1. -1. -1. -1. -1. -1.]]
  [[-1. -1. -1. -1. -1. -1. -1.]]
pattern 3
_____________________________
  [[-1. -1. -1. -1.  1. -1. -1.]]
  [[-1. -1. -1. -1.  1. -1. -1.]]
pattern 4
_____________________________
  [[-1. -1. -1. -1. -1.  1. -1.]]
  [[-1. -1. -1. -1. -1.  1. -1.]]
pattern 5
_____________________________
  [[-1. -1. -1. -1. -1. -1.  1.]]
  [[-1. -1. -1. -1. -1. -1.  1.]]
pattern 6
_____________________________
  [[-1. -1.  1. -1. -1. -1. -1.]]
  [[-1. -1.  1. -1. -1. -1. -1.]]


The results obtained in this section demonstrate an improvement in responses. Notably, as anticipated, the characters 'L' and 'T' exhibit notably superior performance, as evidenced in the outcomes.

# Q7

As previously noted, the expected improvement in response occurs when the letters are orthogonal to each other. For instance, the Hebbian neuron is unlikely to distinguish between 'E' and 'A', whereas 'T' and 'L' are completely orthogonal, thereby facilitating recognition of these characters.

Utilizing both the letters 'L' and 'T', we observed the most optimal responses from these characters, in line with our expectations

Although the Hebbian neuron may not be the most efficient approach for character recognition, it serves as a commendable initial step in the field of neural networks.